### ISSUE TITLE
Competitor comparison not working

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#222]
When opening [https://cubecomp.de/go16/de/comparison](https://cubecomp.de/go16/de/comparison) I get the following error message:

`Liquid error: undefined method `competitors' for nil:NilClass`

It's strange that on other competition sites everything works as expected  (e.g. [here](https://cubecomp.de/so15/de/comparison)), although the files are identical in the admin interface.

**Comment by fw42** [comment]
I think this is because the event handles are all wrong... Should be "3" instead of "333" etc..

Was probably related to https://github.com/fw42/cubecomp/issues/219#issuecomment-203682734.

Basically, the code only shows comparisons for official WCA events, but because you are not using the default event codes, it can't find any events that seem like official WCA events.

The error message is bad though. Will change it to show something more obvious.

**Comment by fw42** [comment]
I'm gonna try to fix this in a smarter way.. You don't have to change all your handles if you don't want to. Give me a few minutes.

**Comment by fw42** [comment]
@Laura-O this is fixed now, thanks for the bug report

**Comment by Laura-O** [comment]
Great, thanks!
